# Generated by Django 4.2.1 on 2023-06-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
